arm_unit_tests_task:

  arm_container:
    image: ghcr.io/ovn-org/ovn-tests:fedora
    memory: 4G
    cpu: 2

  env:
    ARCH: aarch64
    CIRRUS_CLONE_SUBMODULES: true
    PATH: ${HOME}/bin:${HOME}/.local/bin:${PATH}
    matrix:
      - CC: gcc
        TESTSUITE: test
        TEST_RANGE: -500
      - CC: gcc
        TESTSUITE: test
        TEST_RANGE: 501-1000
      - CC: gcc
        TESTSUITE: test
        TEST_RANGE: 1001-
      - CC: clang
        TESTSUITE: test
        TEST_RANGE: -500
      - CC: clang
        TESTSUITE: test
        TEST_RANGE: 501-1000
      - CC: clang
        TESTSUITE: test
        TEST_RANGE: 1001-

  name: ARM64 ${CC} ${TESTSUITE} ${TEST_RANGE}

  build_script:
    - ./.ci/linux-build.sh
